name=DFRobot_IRPositionV2
version=1.0.0
author=DFRobot
maintainer=thdyyl<yuanlong.yu@dfrobot.com>
sentence=Standard library for DFRobot IR Position V2 sensor.(SKU:SEN0701)
paragraph=DFRobot_IRPositionV2 tracks up to 16 IR light sources via PAJ7025R2 and a CS32 I2C bridge.
category=Sensors
url=https://github.com/DFRobot/DFRobot_IRPositionV2
architectures=*

